# Generated by Django 4.0.4 on 2022-05-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["first_name", "last_name"]},
        ),
    ]
