# Generated by Django 4.0.4 on 2022-05-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="app_label",
            field=models.CharField(default="ui", max_length=40),
            preserve_default=False,
        ),
    ]
