# Generated by Django 4.0.4 on 2022-05-11 04:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Extension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("username", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
