# Generated by Django 4.0.4 on 2022-05-11 04:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pbx", "0001_initial"),
    ]

    operations = [
        # Commented due an error in the migration
        # migrations.AddField(
        #     model_name="extension",
        #     name="user",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.SET_NULL,
        #         to=settings.AUTH_USER_MODEL,
        #     ),
        # ),
    ]
