# Generated by Django 4.0.4 on 2022-05-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0003_context_sipaor_sipauth_sipendpoint_extension_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="context",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
