# Generated by Django 4.0.4 on 2022-05-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0004_alter_context_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="context",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pbx.context",
            ),
        ),
    ]
