# Generated by Django 4.0.4 on 2022-08-20 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0005_alter_extension_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="SipContacts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="pk",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sip_id",
                    models.CharField(
                        blank=True, db_column="id", max_length=40, unique=True
                    ),
                ),
                ("uri", models.CharField(default=None, max_length=255, null=True)),
                ("expiration_time", models.IntegerField(default=None, null=True)),
                ("qualify_frequency", models.IntegerField(default=None, null=True)),
                (
                    "outbound_proxy",
                    models.CharField(default=None, max_length=40, null=True),
                ),
                ("path", models.TextField()),
                (
                    "user_agent",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("qualify_timeout", models.FloatField(default=None, null=True)),
                (
                    "reg_server",
                    models.CharField(default=None, max_length=20, null=True),
                ),
                (
                    "authenticate_qualify",
                    models.SlugField(
                        choices=[("yes", "yes"), ("no", "no")], default=None, null=True
                    ),
                ),
                ("via_addr", models.CharField(default=None, max_length=40, null=True)),
                ("via_port", models.IntegerField(default=None, null=True)),
                ("call_id", models.CharField(default=None, max_length=255, null=True)),
                ("endpoint", models.CharField(default=None, max_length=40, null=True)),
                (
                    "prune_on_boot",
                    models.SlugField(
                        choices=[("yes", "yes"), ("no", "no")], default=None, null=True
                    ),
                ),
                (
                    "extension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pbx.extension"
                    ),
                ),
            ],
            options={
                "unique_together": {("sip_id", "reg_server")},
            },
        ),
    ]
