# Generated by Django 4.0.4 on 2022-08-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0009_sipcontact_alter_sipaor_sip_id_alter_sipauth_sip_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sipcontact",
            name="extension",
        ),
    ]
