# Generated by Django 4.0.4 on 2022-08-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0010_remove_sipcontact_extension_alter_sipcontact_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SipContact",
        ),
    ]
