# Generated by Django 4.0.4 on 2022-08-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0010_remove_sipcontact_extension_alter_sipcontact_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sipcontact",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="sipcontact",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="sipcontact",
            unique_together={("id", "reg_server")},
        ),
        migrations.RemoveField(
            model_name="sipcontact",
            name="sip_id",
        ),
    ]
