# Generated by Django 4.0.4 on 2022-08-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0010_remove_sipcontact_extension_alter_sipcontact_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sipcontact",
            name="id",
        ),
        migrations.AlterField(
            model_name="sipcontact",
            name="sip_id",
            field=models.CharField(
                blank=True,
                db_column="id",
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
