# Generated by Django 4.0.4 on 2022-08-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0011_delete_sipcontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="SipContact",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("uri", models.CharField(default=None, max_length=255, null=True)),
                ("expiration_time", models.IntegerField(default=None, null=True)),
                ("qualify_frequency", models.IntegerField(default=None, null=True)),
                (
                    "outbound_proxy",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("path", models.TextField()),
                (
                    "user_agent",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("qualify_timeout", models.FloatField(default=None, null=True)),
                (
                    "reg_server",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "authenticate_qualify",
                    models.SlugField(
                        choices=[("yes", "yes"), ("no", "no")], default=None, null=True
                    ),
                ),
                ("via_addr", models.CharField(default=None, max_length=255, null=True)),
                ("via_port", models.IntegerField(default=None, null=True)),
                ("call_id", models.CharField(default=None, max_length=255, null=True)),
                ("endpoint", models.CharField(default=None, max_length=255, null=True)),
                (
                    "prune_on_boot",
                    models.SlugField(
                        choices=[("yes", "yes"), ("no", "no")], default=None, null=True
                    ),
                ),
            ],
            options={
                "unique_together": {("id", "reg_server")},
            },
        ),
    ]
