# Generated by Django 4.0.4 on 2022-08-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0012_sipcontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sipendpoint",
            name="rtp_symmetric",
            field=models.BooleanField(default=True),
        ),
    ]
