# Generated by Django 4.1 on 2022-08-25 19:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0013_alter_sipendpoint_rtp_symmetric"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialplan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exten", models.CharField(max_length=255)),
                ("priority", models.IntegerField()),
                ("app", models.CharField(max_length=255)),
                ("appdata", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "context",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pbx.context",
                    ),
                ),
            ],
            options={
                "unique_together": {("context", "exten", "priority")},
            },
        ),
        migrations.RemoveField(
            model_name="sipaor",
            name="extension",
        ),
        migrations.RemoveField(
            model_name="sipauth",
            name="extension",
        ),
        migrations.DeleteModel(
            name="SipContact",
        ),
        migrations.RemoveField(
            model_name="sipendpoint",
            name="aors",
        ),
        migrations.RemoveField(
            model_name="sipendpoint",
            name="auth",
        ),
        migrations.RemoveField(
            model_name="sipendpoint",
            name="extension",
        ),
        migrations.CreateModel(
            name="DialplanExtension",
            fields=[
                (
                    "dialplan_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pbx.dialplan",
                    ),
                ),
                (
                    "extension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pbx.extension"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pbx.dialplan",),
        ),
        migrations.DeleteModel(
            name="SipAor",
        ),
        migrations.DeleteModel(
            name="SipAuth",
        ),
        migrations.DeleteModel(
            name="SipEndpoint",
        ),
    ]
