# Generated by Django 4.1 on 2022-08-25 19:06

from django.db import migrations


def recreate_extensions(apps, schema_editor):
    Extension = apps.get_model("pbx", "Extension")
    SipEndpoint = apps.get_model("pbx", "SipEndpoint")
    for extension in Extension.objects.all():
        try:
            SipEndpoint.objects.get(extension=extension)
        except SipEndpoint.DoesNotExist:
            SipEndpoint.objects.create_extension(
                extension,
                username=extension.username,
                password=extension.password,
                context=extension.context,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0015_sipaor_sipauth_sipendpoint_sipcontact"),
    ]

    operations = [
        migrations.RunPython(
            recreate_extensions, reverse_code=migrations.RunPython.noop
        ),
    ]
