# Generated by Django 4.1 on 2022-08-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0017_create_asterisk_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dialplanextension",
            name="dialplan_ptr",
        ),
        migrations.RemoveField(
            model_name="dialplanextension",
            name="extension",
        ),
        migrations.DeleteModel(
            name="Dialplan",
        ),
        migrations.DeleteModel(
            name="DialplanExtension",
        ),
    ]
