# Generated by Django 4.1 on 2022-08-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0018_remove_dialplanextension_dialplan_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SipAor",
        ),
        migrations.DeleteModel(
            name="SipAuth",
        ),
        migrations.DeleteModel(
            name="SipEndpoint",
        ),
    ]
