# Generated by Django 4.1 on 2022-08-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbx", "0021_alter_extension_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sipaor",
            name="sip_id",
            field=models.CharField(
                blank=True, db_column="id", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sipauth",
            name="sip_id",
            field=models.CharField(
                blank=True, db_column="id", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sipendpoint",
            name="sip_id",
            field=models.CharField(
                blank=True, db_column="id", max_length=255, null=True, unique=True
            ),
        ),
    ]
