# Generated by Django 4.0.4 on 2022-05-10 00:17

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0002_notification_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 5, 10, 0, 17, 10, 800022, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
