# Generated by Django 4.0.4 on 2022-05-10 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0003_alter_notification_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
