set -e

set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	    CREATE DATABASE $ASTERISK_DB;
	    GRANT ALL PRIVILEGES ON DATABASE $ASTERISK_DB TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	    CREATE DATABASE $PROMETEUSPBX_DB;
	    GRANT ALL PRIVILEGES ON DATABASE $PROMETEUSPBX_DB TO $POSTGRES_USER;
EOSQL