# Generated by Django 4.0.4 on 2022-04-17 02:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PjSipAor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="pk",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pjsip_id",
                    models.CharField(
                        blank=True, db_column="id", max_length=40, unique=True
                    ),
                ),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "default_expiration",
                    models.IntegerField(blank=True, default=120, null=True),
                ),
                ("mailboxes", models.CharField(blank=True, max_length=80, null=True)),
                ("max_contacts", models.IntegerField(blank=True, default=5, null=True)),
                (
                    "minimum_expiration",
                    models.IntegerField(blank=True, default=60, null=True),
                ),
                ("remove_existing", models.TextField(blank=True, null=True)),
                (
                    "qualify_frequency",
                    models.IntegerField(blank=True, default=60, null=True),
                ),
                ("authenticate_qualify", models.BooleanField(default=True)),
                (
                    "maximum_expiration",
                    models.IntegerField(blank=True, default=3600, null=True),
                ),
                (
                    "outbound_proxy",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("support_path", models.BooleanField(default=True)),
                ("qualify_timeout", models.FloatField(blank=True, null=True)),
                (
                    "voicemail_extension",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PjSipAuth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="pk",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pjsip_id",
                    models.CharField(
                        blank=True, db_column="id", max_length=40, unique=True
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("userpass", "User Password"),
                            ("md5", "md5"),
                            ("google_oauth", "google_oauth"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("nonce_lifetime", models.IntegerField(blank=True, null=True)),
                ("md5_cred", models.CharField(blank=True, max_length=40, null=True)),
                ("password", models.CharField(max_length=80)),
                ("realm", models.CharField(blank=True, max_length=40, null=True)),
                ("username", models.CharField(max_length=40, unique=True)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "oauth_clientid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "oauth_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PjSipEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="pk",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pjsip_id",
                    models.CharField(
                        blank=True, db_column="id", max_length=40, unique=True
                    ),
                ),
                ("accept_multiple_sdp_answers", models.BooleanField(default=False)),
                ("accountcode", models.CharField(blank=True, max_length=80, null=True)),
                ("acl", models.CharField(blank=True, max_length=40)),
                ("aggregate_mwi", models.BooleanField(default=True)),
                ("allow", models.CharField(default="alaw,ulaw", max_length=200)),
                ("allow_overlap", models.BooleanField(default=True)),
                ("allow_subscribe", models.BooleanField(default=True)),
                ("allow_transfer", models.BooleanField(default=True)),
                ("allow_unauthenticated_options", models.BooleanField(default=False)),
                ("asymmetric_rtp_codec", models.BooleanField(default=False)),
                ("bind_rtp_to_media_address", models.BooleanField(default=False)),
                ("bundle", models.BooleanField(default=False)),
                ("call_group", models.CharField(blank=True, max_length=40, null=True)),
                ("callerid", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "callerid_privacy",
                    models.CharField(
                        choices=[
                            ("allowed_not_screened", "allowed_not_screened"),
                            ("allowed_passed_screened", "allowed_passed_screened"),
                            ("allowed_failed_screened", "allowed_failed_screened"),
                            ("allowed", "allowed"),
                            ("prohib_not_screened", "Prohib Not Screened"),
                            ("prohib", "prohib"),
                            ("unavailable", "unavailable"),
                        ],
                        default="allowed_not_screened",
                        max_length=40,
                    ),
                ),
                (
                    "callerid_tag",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "codec_prefs_incoming_answer",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "codec_prefs_incoming_offer",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "codec_prefs_outgoing_answer",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "codec_prefs_outgoing_offer",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "connected_line_method",
                    models.CharField(
                        choices=[
                            ("invite", "invite"),
                            ("reinvite", "reinvite"),
                            ("update", "update"),
                        ],
                        default="invite",
                        max_length=40,
                    ),
                ),
                ("contact_acl", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "contact_deny",
                    models.CharField(blank=True, max_length=95, null=True),
                ),
                (
                    "contact_permit",
                    models.CharField(blank=True, max_length=95, null=True),
                ),
                (
                    "contact_user",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("context", models.CharField(blank=True, max_length=40, null=True)),
                ("cos_audio", models.IntegerField(blank=True, null=True)),
                ("cos_video", models.IntegerField(blank=True, null=True)),
                ("deny", models.CharField(blank=True, max_length=95, null=True)),
                ("device_state_busy_at", models.IntegerField(blank=True, null=True)),
                ("direct_media", models.BooleanField(default=False)),
                (
                    "direct_media_glare_mitigation",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("outgoing", "outgoing"),
                            ("incoming", "incoming"),
                        ],
                        default="none",
                        max_length=40,
                    ),
                ),
                (
                    "direct_media_method",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("outgoing", "outgoing"),
                            ("incoming", "incoming"),
                        ],
                        default="invite",
                        max_length=40,
                    ),
                ),
                ("disable_direct_media_on_nat", models.BooleanField(default=False)),
                ("disallow", models.CharField(default="all", max_length=200)),
                ("dtls_auto_generate_cert", models.BooleanField(default=False)),
                (
                    "dtls_ca_file",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "dtls_ca_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "dtls_cert_file",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "dtls_cipher",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "dtls_fingerprint",
                    models.CharField(
                        choices=[("SHA-1", "SHA-1"), ("SHA-256", "SHA-256")],
                        default="SHA-256",
                        max_length=40,
                    ),
                ),
                (
                    "dtls_private_key",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("dtls_rekey", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "dtls_setup",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("passive", "passive"),
                            ("actpass", "actpass"),
                        ],
                        default="active",
                        max_length=40,
                    ),
                ),
                (
                    "dtls_verify",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no")],
                        default="no",
                        max_length=10,
                    ),
                ),
                (
                    "dtmf_mode",
                    models.CharField(
                        choices=[
                            ("rfc4733", "rfc4733"),
                            ("inband", "inband"),
                            ("info", "info"),
                            ("auto", "auto"),
                            ("auto_info", "auto_info"),
                        ],
                        default="rfc4733",
                        max_length=40,
                    ),
                ),
                (
                    "external_media_address",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("fax_detect", models.BooleanField(default=False)),
                ("fax_detect_timeout", models.IntegerField(blank=True, default=0)),
                ("follow_early_media_fork", models.BooleanField(default=True)),
                ("force_avp", models.BooleanField(default=False)),
                ("force_rport", models.BooleanField(default=True)),
                (
                    "from_domain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("from_user", models.CharField(blank=True, max_length=40, null=True)),
                ("g726_non_standard", models.BooleanField(default=False)),
                ("ice_support", models.BooleanField(default=False)),
                ("identify_by", models.CharField(blank=True, max_length=80, null=True)),
                ("ignore_183_without_sdp", models.BooleanField(default=False)),
                ("inband_progress", models.BooleanField(default=False)),
                (
                    "incoming_mwi_mailbox",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=40, null=True)),
                ("mailboxes", models.CharField(blank=True, max_length=40, null=True)),
                ("max_audio_streams", models.IntegerField(blank=True, default=1)),
                ("max_video_streams", models.IntegerField(blank=True, default=1)),
                (
                    "media_address",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "media_encryption",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no")],
                        default="no",
                        max_length=10,
                    ),
                ),
                ("media_encryption_optimistic", models.BooleanField(default=False)),
                ("media_use_received_transport", models.BooleanField(default=False)),
                (
                    "message_context",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("moh_passthrough", models.BooleanField(default=False)),
                (
                    "moh_suggest",
                    models.CharField(blank=True, default="default", max_length=40),
                ),
                (
                    "mwi_from_user",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "mwi_subscribe_replaces_unsolicited",
                    models.BooleanField(default=False),
                ),
                (
                    "named_call_group",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "named_pickup_group",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("notify_early_inuse_ringing", models.BooleanField(default=False)),
                ("one_touch_recording", models.BooleanField(default=False)),
                (
                    "outbound_auth",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "outbound_proxy",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("permit", models.CharField(blank=True, max_length=95, null=True)),
                (
                    "pickup_group",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("preferred_codec_only", models.BooleanField(default=False)),
                (
                    "record_off_feature",
                    models.CharField(blank=True, default="automixmon", max_length=40),
                ),
                (
                    "record_on_feature",
                    models.CharField(blank=True, default="automixmon", max_length=40),
                ),
                (
                    "redirect_method",
                    models.CharField(
                        choices=[
                            ("user", "user"),
                            ("uri_core", "uri_core"),
                            ("uri_pjsip", "uri_pjsip"),
                        ],
                        default="user",
                        max_length=40,
                    ),
                ),
                ("refer_blind_progress", models.BooleanField(default=False)),
                ("rel100", models.BooleanField(db_column="100rel", default=True)),
                ("rewrite_contact", models.BooleanField(default=True)),
                ("rpid_immediate", models.BooleanField(default=False)),
                ("rtcp_mux", models.BooleanField(default=False)),
                ("rtp_engine", models.CharField(blank=True, max_length=40, null=True)),
                ("rtp_ipv6", models.BooleanField(default=False)),
                ("rtp_keepalive", models.IntegerField(blank=True, default=0)),
                ("rtp_symmetric", models.BooleanField(default=False)),
                ("rtp_timeout", models.IntegerField(blank=True, default=0)),
                ("rtp_timeout_hold", models.IntegerField(blank=True, default=0)),
                ("sdp_owner", models.CharField(blank=True, max_length=40, null=True)),
                ("sdp_session", models.CharField(blank=True, max_length=40, null=True)),
                ("send_connected_line", models.BooleanField(default=True)),
                ("send_diversion", models.BooleanField(default=True)),
                ("send_history_info", models.BooleanField(default=False)),
                ("send_pai", models.BooleanField(default=False)),
                ("send_rpid", models.BooleanField(default=False)),
                ("set_var", models.TextField(blank=True, null=True)),
                ("srtp_tag_32", models.BooleanField(default=False)),
                ("stir_shaken", models.BooleanField(default=False)),
                ("sub_min_expiry", models.IntegerField(blank=True, default=0)),
                (
                    "subscribe_context",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("suppress_q850_reason_headers", models.BooleanField(default=False)),
                ("t38_udptl", models.BooleanField(default=False)),
                (
                    "t38_udptl_ec",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("fec", "fec"),
                            ("redundancy", "redundancy"),
                        ],
                        default="none",
                        max_length=40,
                    ),
                ),
                ("t38_udptl_ipv6", models.BooleanField(default=False)),
                ("t38_udptl_maxdatagram", models.IntegerField(blank=True, default=0)),
                ("t38_udptl_nat", models.BooleanField(default=False)),
                ("timers", models.BooleanField(default=True)),
                ("timers_min_se", models.IntegerField(blank=True, default=90)),
                ("timers_sess_expires", models.IntegerField(blank=True, default=1800)),
                ("tone_zone", models.CharField(blank=True, max_length=40, null=True)),
                ("tos_audio", models.CharField(blank=True, max_length=10, null=True)),
                ("tos_video", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "transport",
                    models.CharField(
                        blank=True, default="transport-udp", max_length=40, null=True
                    ),
                ),
                ("trust_connected_line", models.BooleanField(default=True)),
                ("trust_id_inbound", models.BooleanField(default=False)),
                ("trust_id_outbound", models.BooleanField(default=False)),
                ("use_avpf", models.BooleanField(default=False)),
                ("use_ptime", models.BooleanField(default=False)),
                ("user_eq_phone", models.BooleanField(default=False)),
                (
                    "voicemail_extension",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("webrtc", models.BooleanField(default=False)),
                (
                    "aors",
                    models.ForeignKey(
                        db_column="aors",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pjsip.pjsipaor",
                        to_field="pjsip_id",
                    ),
                ),
                (
                    "auth",
                    models.ForeignKey(
                        db_column="auth",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pjsip.pjsipauth",
                        to_field="pjsip_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
